# Generated by Django 2.1.5 on 2019-02-08 08:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AreaUnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('path_file', models.CharField(max_length=1000)),
                ('checksum', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('bathrooms', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField(null=True)),
                ('property_size', models.IntegerField(null=True)),
                ('year_built', models.IntegerField(null=True)),
                ('area_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.AreaUnitModel')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.CityModel')),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.HomeTypeModel')),
            ],
        ),
        migrations.CreateModel(
            name='TaxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ZillowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zillow_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZRentInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rentzestimate_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rentzestimate_last_updated', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZSaleInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('zestimate_last_updated', models.DateField(auto_now=True)),
                ('zestimate_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='zillowmodel',
            name='z_rent_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ZRentInformationModel'),
        ),
        migrations.AddField(
            model_name='zillowmodel',
            name='z_sale_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ZSaleInformationModel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='price_history',
            field=models.ManyToManyField(to='sales.PriceHistoryModel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ResidenceModel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.TaxModel'),
        ),
        migrations.AddField(
            model_name='announcementmodel',
            name='zillow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ZillowModel'),
        ),
    ]
